### ISSUE TITLE
在window server2019搜图会返回空白图片

### ISSUE THREAD

**Issue by OrangeMiracle** [cpuopt/nonebot_plugin_imgexploration#10]
在window server2019搜图会返回空白图片

如图，我在windows server 2019的系统上配置了机器人，字体也安装了，但是搜图会返回空白图片
![image](https://user-images.githubusercontent.com/100971728/223602695-e4a387fa-4e24-4211-aae0-b887892d20de.png)

**Comment by OrangeMiracle** [comment]
![image](https://user-images.githubusercontent.com/100971728/223602855-9b8c740c-dfc2-4750-8d48-f6b6f1dc97be.png)

**Comment by cpuopt** [comment]
搜图引擎需要稳定的科学上网环境
尝试在浏览器打开google等搜图网站，如果不能打开或要求人机验证，需要换更稳定的梯子

**Comment by OrangeMiracle** [comment]
我在国外不需要梯子，但是我的专业版win10是可以正常使用这个插件的

**Comment by cpuopt** [comment]
用浏览器访问试试，看是不是服务器的dns问题

**Comment by OrangeMiracle** [comment]
DNS我使用了自动获取，浏览器可以搜到结果

**Comment by cpuopt** [comment]
试下能访问这个网站并且上传图片吗
https://imgops.com/
从日志10:16:15来看，上传图片没有花费时间，可能是上传失败了

**Comment by cpuopt** [comment]
我遇到了类似的情况，经过排查我发现原因是上传图片到imgops.com获取的链接字段是br压缩的，
在没有安装brotli或brotlicffi库的情况下不能正确解码，httpx也不会报错或提醒，
解决办法就是pip install brotli就可以了。
现在的版本我把brotli添加了依赖，在安装插件时会自动安装brotli，你可以再尝试一下
