### ISSUE TITLE
ubuntu server安装字体后报错

### ISSUE THREAD

**Issue by canxin121** [cpuopt/nonebot_plugin_imgexploration#11]
File "/nb/cxbot/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 255, in __init__
    self.font = core.getfont(
OSError: cannot open resource

报错详情
![image](https://user-images.githubusercontent.com/69547456/224033793-1e9b4d5e-94a8-4d82-9aa0-cbc365126d34.png)

下面是字体安装情况
![image](https://user-images.githubusercontent.com/69547456/224032403-ae7cbb1b-7ea2-4086-a667-38df0024b24a.png)
![image](https://user-images.githubusercontent.com/69547456/224032513-22d2ca0d-75f1-41d0-876e-f0fd914d0f3f.png)

**Comment by cpuopt** [comment]
fc-cache -f -v
或重启机器

**Comment by cpuopt** [comment]
或者是当前用户没有字体文件的读权限

**Comment by canxin121** [comment]
都试了，还是同样报错，emmm
