### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by Mokouthebest** [cpuopt/nonebot_plugin_imgexploration#13]
![image](https://user-images.githubusercontent.com/32454843/231080494-d91152a6-56b0-434a-bcbb-f9b21335e416.png)

**Comment by cpuopt** [comment]
这是频道插件加载的报错，重新用nb-cli创建项目，用nb plugin install按顺序安装

**Comment by Mokouthebest** [comment]
好 我试试

**Comment by Mokouthebest** [comment]
已解决 感谢
