### ISSUE TITLE
搜索图片时返回空白图片

### ISSUE THREAD

**Issue by KamiXiaoLing** [cpuopt/nonebot_plugin_imgexploration#15]
06-10 12:19:33 [SUCCESS] nonebot_plugin_imgexploration | 获取到图片: https://c2cpicdw.qpic.cn/offpic_new/0/3346096023-1805399130-04709CC7B86067454BC575B8F100157F/0?term=3
06-10 12:19:33 [INFO] nonebot_plugin_gocqhttp | [3456214440] 发送好友 334xxxxxx)  的消息: [{"type":  ... (1330599130)
06-10 12:19:34 [INFO] nonebot_plugin_imgexploration | 图片上传到Imgops
06-10 12:19:35 [INFO] nonebot_plugin_imgexploration | saucenao searching...
06-10 12:19:36 [INFO] nonebot_plugin_imgexploration | ascii2d searching...
06-10 12:19:36 [INFO] nonebot_plugin_imgexploration | google searching...
06-10 12:19:36 [INFO] nonebot_plugin_imgexploration | yandex searching...
06-10 12:19:37 [SUCCESS] nonebot_plugin_imgexploration | saucenao result:0
06-10 12:19:37 [SUCCESS] nonebot_plugin_imgexploration | ascii2d result:0
06-10 12:19:38 [ERROR] nonebot_plugin_imgexploration | substring not found
06-10 12:19:38 [SUCCESS] nonebot_plugin_imgexploration | google result:0
06-10 12:19:38 [ERROR] nonebot_plugin_imgexploration | list index out of range
06-10 12:19:38 [INFO] nonebot_plugin_imgexploration | Drawing... total:0

**Comment by cpuopt** [comment]
https://github.com/cpuopt/nonebot_plugin_imgexploration/issues/10#issuecomment-1554010202
