### ISSUE TITLE
能否提供稍微详细的获取google cookie的方法

### ISSUE THREAD

**Issue by niucattle** [cpuopt/nonebot_plugin_imgexploration#17]
我在www.google.com打开控制台输入console.log(document.cookie)，然后复制得到的cookie填入env，
![image](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/118875129/73fcfda0-fe55-49ce-8391-faa163b699b6)
![UT4C{(E8G$)GLA_W54OAH22](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/118875129/e963bc3b-4627-48e3-88dd-15390071a4c7)
在网络里的cookie是这样一大串
![QY@H)F{PI32JNIF90PCPSYB](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/118875129/f5d048ae-9f3d-400d-be8a-401cfd77ca7b)
填入是这样
![9D F{KVA@ROE%$_G$01~UFL](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/118875129/fb1144bf-7be6-4f6a-ad86-8d9ab334d512)
报错是这样
![image](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/118875129/6c368c47-c64e-459d-be67-b753d4aa7fad)

**Comment by cpuopt** [comment]
加一个双引号引起来 google_cookies=""

**Comment by niucattle** [comment]
解决了 感谢！
