### ISSUE TITLE
如何设置谷歌搜索结果的安全搜索设置

### ISSUE THREAD

**Issue by miku239** [cpuopt/nonebot_plugin_imgexploration#19]
谷歌搜索的返回结果中有些结果被高度迷糊无法辨识，在网页版搜索中有“安全搜索设置”功能，其中 可以关闭安全搜索功能，但是如何在本插件中进行设置呢？
![QQ截图20230907212030](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/56502504/ca9ccd15-7bea-4bf3-84fc-f05fbcda9428)

我尝试过更新cookie为设置后的cookie，但是没有效果

**Comment by cpuopt** [comment]
暂时没有这个功能，因为是在qq中使用，还是不宜出现暴露的图片。
