### ISSUE TITLE
搜索结果有链接，但是不显示预览图

### ISSUE THREAD

**Issue by annko11** [cpuopt/nonebot_plugin_imgexploration#20]
![YD$5~TLEZDS%2N4FR1UEQ@I](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/139084066/16aad01c-613b-4032-8378-a86b389cde94)
如图所示，谷歌搜索的预览图全为空白，ascii2d有时候有，有时候也是空白
之前一直都是好的，最近变成这样的，更新插件、重新获取cookie都试过，还是没解决
报错如下
![)EP2BF0WU5M6_2R P` %L@B](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/139084066/1a67f2a2-4add-4c0e-a085-d9f59fa7ba92)

![6E2%RCQ45})95SPDGJ I57](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/139084066/59585e70-e402-416b-87af-f15b341cfac0)

![F2BRS 33 OX{C4K3E4)`@9K](https://github.com/cpuopt/nonebot_plugin_imgexploration/assets/139084066/88954e36-57d3-4046-89a8-50ce00ea43e1)

**Comment by cpuopt** [comment]
更换比较稳定、用的人少的机场或节点可以解决
