### ISSUE TITLE
无法解析来自google的返回，来自ascii2d、pixiv、twitter的缩略图不显示

### ISSUE THREAD

**Issue by KiriSuoh** [cpuopt/nonebot_plugin_imgexploration#23]
环境：win10x64，python3.12.4，nonebot2，实现端LiteLoaderQQNT 

twitter的结果确实是图片，但不显示缩略图。
![5b6c883666656c2a8d99f0364fd0247a_720](https://github.com/user-attachments/assets/26266802-a537-4730-9177-f662ba2c7f21)

搜网图，没有来自google的输出，控制台看到google有结果时返回的数据看报错是无法解析
![ca4683ca1c4ebb539efb8639d17d0df8](https://github.com/user-attachments/assets/02ae9b72-7b0d-43eb-9403-a1b9bb86ec82)
![0e9497ef9bf6e26bb06939b29229339e_720](https://github.com/user-attachments/assets/428c0bd7-3a10-494e-9471-e840c4aa253c)

配置好了代理和cookie
![3ef8b95eabb2feea7e226ca0671e5a6d](https://github.com/user-attachments/assets/77938068-0d70-4cbd-9e08-447ee5f191d6)

**Comment by cpuopt** [comment]
28281d589921f1f96be7b9f17dd6487668da6e0e

1.修复 无法解析google搜图结果的问题 
![QQ截图20240727172402](https://github.com/user-attachments/assets/3294e5ef-fa10-4d58-a624-f98ae6a99e33)

![QQ图片20240727172311](https://github.com/user-attachments/assets/bcae010b-79fd-4071-8287-53e2a61b44b4)

2.修复 缩略图下载失败的问题
![QQ图片20240727172321](https://github.com/user-attachments/assets/0d8f7f80-2078-4c7d-bd94-51944273f064)

都是已知已修复的问题，已经更新github和pypi版本，更新到0.4.2即可
另外使用某些地区、某些节点可能会导致搜图无结果，实测建议用日本节点

**Comment by KiriSuoh** [comment]
感谢，好不少了，缩略图已正常，但google用日本节点也没结果

更新后有时会出现完全没结果的白
![4B0754EE6989C80CB7FE6E60187A4C8A](https://github.com/user-attachments/assets/d8595827-b05e-4ba3-a03e-8345228badb5)
对应报错
![CADF9DC2C54A716B731073BE304271D5](https://github.com/user-attachments/assets/eb196afd-24c4-4935-b33e-21c9b4193df7)


已使用日本节点但google没结果
![QQ截图20240728130717](https://github.com/user-attachments/assets/fe8c90f1-6ff6-4fab-bddf-98cbc0a4fc7a)
![QQ截图20240728130224](https://github.com/user-attachments/assets/3fb0ffb1-f4d2-439e-a52a-a32b80041505)
![8C43C92C83336ABB29C0B0C848416051](https://github.com/user-attachments/assets/b7865c4e-e351-43f6-a463-c4a1133075d8)

**Comment by cpuopt** [comment]
全白无结果看报错第一行的上一行链接能不能打开，报这个BytesIO的错误大多是协议实现端获取的图片链接错误，例如某些旧版本的openshamrock。
google获取不到大概率是因为跳了人机验证，换节点重新登google账号重新拿cookie有概率可解决。
