### ISSUE TITLE
搜图不显示SauceNAO结果

### ISSUE THREAD

**Issue by BenYangOvO** [cpuopt/nonebot_plugin_imgexploration#24]
已经尝试过直接使用依赖库（kitUIN/PicImageSearch）的示范代码，输入自己的api_key操作，能够正常获取结果。
使用插件时故障表现为返回结果永远显示0。
![20240803011035](https://github.com/user-attachments/assets/060056c1-d59a-4f38-8834-9763ed23fc8d)
虽然返回0，但SauceNAO账户后台的用量统计会照常变动。
其它来源的结果均成功获取，可能不是imgops的问题。
我的能力就到这了，实在不懂咋解决……

**Comment by cpuopt** [comment]
图片发上来

**Comment by BenYangOvO** [comment]
> 图片发上来

以这张图为例
　
![20240803011036](https://gchat.qpic.cn/offpic_new/2765086320//2765086320-4217918003-D4103AD8B07941F8D5D662518437E368/0?term=255&is_origin=0)
　
　
SauceNAO手动能够搜索出93%相似度的结果，但机器人不行
　
![20240803164211](https://github.com/user-attachments/assets/d17255df-0ee5-4d8b-8692-532b2a3cbf77)

**Comment by BenYangOvO** [comment]
偶有例外情况，比如这张
　
![84B8920F242BFC3A379EE2D7F2069A66](https://github.com/user-attachments/assets/1f105207-655a-4c29-91ea-c00401262bde)
　
　
虽然机器人确实能正常搜索
　
![20240803165450](https://github.com/user-attachments/assets/31bf7b0a-7e98-4884-9525-b419d89be456)
　
　
但机器人返回的结果是danbooru链接，而非SauceNAO提供的推特链接

**Comment by cpuopt** [comment]
第一张的原因是结果不包含链接，过滤掉了
第二张的原因是链接取url字段，而不是source字段

**Comment by BenYangOvO** [comment]
Ok，这下理解了
