### ISSUE TITLE
无dic是种什么情况

### ISSUE THREAD

**Issue by Rakastu** [cpuopt/nonebot_plugin_imgexploration#26]
![image](https://github.com/user-attachments/assets/943ba9af-4fdb-4ba4-8990-07ec51a673a6)

**Comment by cpuopt** [comment]
你拿这张图上yandex搜一下看有结果吗

**Comment by Rakastu** [comment]
![2](https://github.com/user-attachments/assets/9e722192-0b50-49e8-a8c9-90de0ce9c616)
确实能搜到

**Comment by cpuopt** [comment]
反正现在ascii2d有cf盾，google和yandex也是玄学搜图，google时不时的预览图出不来。我自己一直挂着机器人在用的，一般都能搜出结果。你要想看报错的原因就把搜图结果的html存下来看吧，无外乎跳了人机验证、imgops图床挂了、cookie过期了之类的。另外ascii2d你要想用的话参考https://www.cpufan.top/index.php/2024/09/19/ascii2d-net-cloudflare/

**Comment by Rakastu** [comment]
好的大佬，确实玄学，多测试了几张已经可以了，感谢
