### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by OrangeMiracle** [cpuopt/nonebot_plugin_imgexploration#9]
发送图片后出现 

[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_imgexploration) failed.

OSError: cannot open resource

**Comment by cpuopt** [comment]
是否安装了字体？
### 2.需要字体    
```
HarmonyOS_Sans_SC_Regular.ttf  
HarmonyOS_Sans_SC_Bold.ttf  
HarmonyOS_Sans_SC_Light.ttf
```
https://developer.harmonyos.com/cn/docs/design/des-guides/font-0000001157868583   
安装到系统字体即可

**Comment by OrangeMiracle** [comment]
错误出现在字体安装后，是否需要重启系统？

因为系统上面我还跑着很多东西，就没重启

**Comment by cpuopt** [comment]
不用重启，截一下完整报错

**Comment by OrangeMiracle** [comment]
emmmm....
他又能用了，不过之前出现错误的时候是我是点开字体文件，然后点击左上角进行安装
这次是，我直接右键字体文件，并选择“为所有用户安装”
我认为是安装的时候没有给到这个字体管理员权限导致的

不过还是感谢解答
